version = 5.6.0
archive_dir = /etc/letsencrypt/archive/phunattakitsupply.com
cert = /etc/letsencrypt/live/phunattakitsupply.com/cert.pem
privkey = /etc/letsencrypt/live/phunattakitsupply.com/privkey.pem
chain = /etc/letsencrypt/live/phunattakitsupply.com/chain.pem
fullchain = /etc/letsencrypt/live/phunattakitsupply.com/fullchain.pem
[renewalparams]
account = 334a81418de86feb31bdc0f129bab61a
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
phunattakitsupply.com = /var/www/certbot
www.phunattakitsupply.com = /var/www/certbot
