name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            set -e

            cd ~/phunuttakitsupply.com

            echo "📦 Pull latest code"
            git pull origin main

            echo "🏗 Build containers"
            docker compose down

            echo "🚀 Start containers (no downtime down)"
            docker compose up -d --build

            # echo "🧹 Clean unused docker resources"
            # docker system prune -f || true

            echo "✅ Deploy completed safely"